

FORMAT_LENGTHS = {
    "b": 1,
    "a": 1024,
    "s": 64,
    "h": 2,
    "i": 4,
}

from format import Format

TYPE_INITIAL = 0
TYPE_KEEPALIVE = 1
TYPE_PRECHUNK = 2
TYPE_CHUNK = 3
TYPE_LEVELSIZE = 4
TYPE_BLOCKCHANGE = 5
TYPE_BLOCKSET = 6
TYPE_SPAWNPOINT = 7
TYPE_PLAYERPOS = 8
TYPE_NINE = 9
TYPE_TEN = 10
TYPE_PLAYERDIR = 11
TYPE_PLAYERLEAVE = 12
TYPE_MESSAGE = 13
TYPE_ERROR = 14

TYPE_FORMATS = {
    TYPE_INITIAL: Format("bssb"),
    TYPE_KEEPALIVE: Format(""),
    TYPE_PRECHUNK: Format(""),
    TYPE_CHUNK: Format("hab"),
    TYPE_LEVELSIZE: Format("hhh"),
    TYPE_BLOCKCHANGE: Format("hhhbb"),
    TYPE_BLOCKSET: Format("hhhb"),
    TYPE_SPAWNPOINT: Format("bshhhbb"),
    TYPE_PLAYERPOS: Format("bhhhbb"),
    TYPE_NINE: Format("bbbbbb"),
    TYPE_TEN: Format("bbbb"),
    TYPE_PLAYERDIR: Format("bbb"),
    TYPE_PLAYERLEAVE: Format("b"),
    TYPE_MESSAGE: Format("bs"),
    TYPE_ERROR: Format("s"),
}

TASK_BLOCKSET = 1
TASK_PLAYERPOS = 2
TASK_MESSAGE = 3
TASK_NEWPLAYER = 4
TASK_PLAYERLEAVE = 5
TASK_PLAYERDIR = 6
TASK_WORLDCHANGE = 7
TASK_ADMINMESSAGE = 8
TASK_WORLDMESSAGE = 9
TASK_ACTION = 10
TASK_SERVERMESSAGE = 11
TASK_PHYSICSON = 12
TASK_PHYSICSOFF = 13
TASK_FLUSH = 14
TASK_BLOCKGET = 15
TASK_STOP = 16
TASK_PLAYERCONNECT = 17
TASK_UNFLOOD = 18
TASK_FWATERON = 19
TASK_FWATEROFF = 20
TASK_PLAYERRESPAWN = 21

COLOUR_BLACK = "&0"
COLOUR_DARKBLUE = "&1"
COLOUR_DARKGREEN = "&2"
COLOUR_DARKCYAN = "&3"
COLOUR_DARKRED = "&4"
COLOUR_DARKPURPLE = "&5"
COLOUR_DARKYELLOW = "&6"
COLOUR_GREY = "&7"
COLOUR_DARKGREY = "&8"
COLOUR_BLUE = "&9"
COLOUR_GREEN = "&a"
COLOUR_CYAN = "&b"
COLOUR_RED = "&c"
COLOUR_PURPLE = "&d"
COLOUR_YELLOW = "&e"
COLOUR_WHITE = "&f"


BLOCK_AIR = 0
BLOCK_ROCK = 1
BLOCK_GRASS = 2
BLOCK_DIRT = 3
BLOCK_STONE = 4
BLOCK_WOOD = 5
BLOCK_PLANT = 6
BLOCK_GROUND_ROCK = 7
BLOCK_WATER = 8
BLOCK_STILL_WATER = 9
BLOCK_LAVA = 10
BLOCK_STILL_LAVA = 11
BLOCK_SAND = 12
BLOCK_GRAVEL = 13
BLOCK_GOLD_ORE = 14
BLOCK_COPPER_ORE = 15
BLOCK_COAL_ORE = 16
BLOCK_LOG = 17
BLOCK_LEAVES = 18
BLOCK_SPONGE = 19
BLOCK_GLASS = 20
BLOCK_RED_CLOTH = 21
BLOCK_ORANGE_CLOTH = 22
BLOCK_YELLOW_CLOTH = 23
BLOCK_LIME_CLOTH = 24
BLOCK_GREEN_CLOTH = 25
BLOCK_TURQUOISE_CLOTH = 26
BLOCK_CYAN_CLOTH = 27
BLOCK_BLUE_CLOTH = 28
BLOCK_INDIGO_CLOTH = 29
BLOCK_VIOLET_CLOTH = 30
BLOCK_PURPLE_CLOTH = 31
BLOCK_MAGENTA_CLOTH = 32
BLOCK_PINK_CLOTH = 33
BLOCK_DARKGREY_CLOTH = 34
BLOCK_GREY_CLOTH = 35
BLOCK_WHITE_CLOTH = 36
BLOCK_YELLOW_FLOWER = 37
BLOCK_RED_FLOWER = 38
BLOCK_BROWN_MUSHROOM = 39
BLOCK_RED_MUSHROOM = 40
BLOCK_GOLD = 41

class ServerFull(Exception):
    pass
